00-intro.Rmd, 01b-AI_Possibilities-what_is_ai.Rmd, 01c-AI_Possibilities-how_ai_works.Rmd, book.bib, resources/dictionary.txt
Adding information about AI Possibilities: How AI works
=> Add some text about data and ML

00-intro.Rmd
Adding more stuff :) 
- Target audience added to Introduction
=> More on Introduction

01b-AI_Possibilities-what_is_ai.Rmd, References.Rmd, book.bib
You can check this using [Color Oracle](https://colororacle.org/).
=> Added Financial Forecasting case study

04e-AI_Policy-creating_your_ai_policy.Rmd
Added a section on the biggest lessons Jeff has learned from writing an AI policy, with an emphasis on things decision makers should consider when they start out.
=> [AI POLICY] adding in Jeff's lessons from writing a policy

04b-AI_Policy-ai_regs_and_laws.Rmd
Slowly beefing up the section on industry-specific regulations with real examples
=> [AI Policy] Industry-specific regulations beefed up slightly

config.yml, index.Rmd
did not see the disclaimer show up, so with more investigation realized there was a colon in the disclaimer text within the config that may have been throwing it off
Nope turns out it was the install - using devtools worked best
=> adding better install cause no config package

02a-Avoiding_Harm-intro.Rmd, quizzes/02a-Avoiding_Harm-Overall_quiz.md, quizzes/02b-Avoiding_Harm-concepts_quiz.md, quizzes/02c-Avoiding_Harm-algorithms_quiz.md, quizzes/02d-Avoiding_Harm-adherence_quiz.md, quizzes/02e-Avoiding_Harm-consent_and_ai.md, quizzes/02f-Avoiding_Harm-idare_and_ai.md, quizzes/02g-Avoiding_Harm-ethical_process_quiz.md
some little tiny things and trying nonsense changes to quizzes for course 2 to try to trigger conversion for coursera, as doing the render_all action didn't do it
=> Little things

04b-AI_Policy-ai_regs_and_laws.Rmd
Making it clearer why people outside the EU should care about the EU AI Act
=> [AI Policy] focusing the section about AI-specific laws

config_automation.yml
@carriewright11 mentioned her quizzes weren't being converted. That is because we haven't turn on quizzes in this repo. This PR will do that:
=> Turn on quiz rendering in config_automation.yml

quizzes/02ba-Avoiding_Harm-concepts_quiz.md
Adding a quiz for the testing training section of the Avoiding Harm miniclass
=> adding quiz for ch from chris

.github/workflows/render-all.yml
I think they get rendered/added in the render_all.yml workflow. - it seems from the logs that they are rendering but not being committed so I am going to try adding a line to add them as well.
=> trying to fix coursera quizzes not showing up

quizzes/02a-Avoiding_Harm-Overall_quiz.md
still not seeing coursera quizzes generated - trying a change to a quiz
=> random change

02a-Avoiding_Harm-intro.Rmd, 02b-Avoiding_Harm-concepts.Rmd, 02f-Avoiding_Harm-idare_and_ai.Rmd, book.bib
added some more learning objectives
wanted to be more aligned with each ch
Also updated based on Jeff's suggestions:
- added more emphasis about AI systems being thought of as better computers
- expanded the inappropriate use section to be more inclusive to more benign cases and suggesting that humans should be involved
- added third category for types of tools for choosing the right tool for the job
- softened /said more about using AI for hiring - instead of saying should not - strongly cautioned and suggested that people be involved at a minimum and suggested consulting experts
=> [Avoiding harm] updating learning objectives and Jeff's updates

03b-Determining-AI-Needs-components.Rmd, 03c-Determining-AI-Needs-determining-needs.Rmd, 03d-Determining-AI-Needs-knowledge.Rmd, 03f-Determining-AI-Needs-interface.Rmd, 03g-Determining-AI-Needs-evaluation.Rmd
Adding Jeff and Sita suggestions here!
Jeff left some comments in the word doc version of these courses and Sita made great edits to the slides! This is me incorporating those suggestions and edits!
=> Jeff and Sita suggestions and edits!

04e-AI_Policy-creating_your_ai_policy.Rmd
Streamlining the considerations chapter to make it read better! Also removed some redundancy as some material was moved elsewhere in the course.
=> [AI Policy] More editing of considerations

04b-AI_Policy-how_to_navigate.Rmd
Adds a section on the elements of an AI policy. Also breaks the first chapter into three parts: why you need an AI policy, elements of an AI policy, and who can advise you on AI issues
=> [AI Policy] adding elements of an AI policy

04a-AI_Policy-intro.Rmd
Just changing the title for now.
=> Edits to intro page for Developing an AI Policy

04c-AI_Policy-how_to_navigate.Rmd
Candace offered great advice on cleaning stuff up and making the text more interesting!
=> [AI Policy] incorporating Candace's edits

index.Rmd
Making the bookdown title match the repo title
=> [General] Adjusting bookdown title

_bookdown.yml
Just changing the order of the chapters for Developing an AI Policy
=> [AI Policy] changing chapter order

04e-AI_Policy-creating_your_ai_policy.Rmd
=> [AI Policy] Amy's edits to considerations chapter

README.md
Making the README match what's actually in the course.
=> [General] Update README.md

index.Rmd
Just changing the title of course 4 in index.Rmd
=> [General] Correcting title of course 4

resources/dictionary.txt
Just adding a name to dictionary.txt because OTTR doesn't recognize it.
=> [General] Add words to dictionary

04c-AI_Policy-how_to_navigate.Rmd
Exactly what the title of this PR says
=> [AI Policy] changing title of AI advisory team chapter

04d-AI_Policy-data_laws.Rmd
Changing the title to Other laws to consider chapter
=> [AI Policy] Changing title of other laws chapter

04b-AI_Policy-ai_regs_and_laws.Rmd
Fixing weird capitalization in the title of the AI acts, orders, and policies chapter
=> [AI Policy] Updating capitalization

04a-AI_Policy-intro.Rmd
After I changed the introduction title, I realized everyone else had it a different way
=> [AI Policy] Reverting course title

About.Rmd
Chris, Monica, Amy, and Jenny are all getting credit for their work on course 4 now
=> [AI Policy] Adding AI Policy contributors and reviewers

01b-AI_Possibilities-what_is_ai.Rmd, 01c-AI_Possibilities-how_ai_works.Rmd, 01d-AI_Possibilities-ai_types.Rmd, 01e-AI_Possibilities-possibilities.Rmd, book.bib, index.Rmd, resources/dictionary.txt
=> [AI Possibilites] Actually getting to the good stuff 🌶️

About.Rmd
Changing an AI Policy shout-out to Jenny to the proper name
=> [General] Updating authors

04c-AI_Policy-how_to_navigate.Rmd
Bookdown was just a wall of text - I added images to break it up a little.
=> [AI Policy] Adding images to first three chapters

04b-AI_Policy-ai_regs_and_laws.Rmd
Exactly what the PR title says. The chapter was a bit "wall of text"
=> [AI Policy] Adding images to AI acts, orders, and regulations

04d-AI_Policy-data_laws.Rmd
Adding images to break up the text in the "Other laws to consider" chapter
=> [AI Policy] Add images to other data laws chapter

04e-AI_Policy-creating_your_ai_policy.Rmd
Adding images to "considerations for creating an AI policy" chapter to make it less text-y and less boring
=> [AI Policy] Add images to considerations chapter

01b-AI_Possibilities-what_is_ai.Rmd, 01c-AI_Possibilities-how_ai_works.Rmd, 01d-AI_Possibilities-ai_types.Rmd, 01e-AI_Possibilities-possibilities.Rmd
You can check this using [Color Oracle](https://colororacle.org/).
=> Add discussion prompts for AI Possibilities

02b-Avoiding_Harm-concepts.Rmd, 02e-Avoiding_Harm-consent_and_ai.Rmd
=> Tiny things

04a-AI_Policy-intro.Rmd
Had a weird half-sentence that I needed to remove
=> [AI Policy] Fix typo in introduction

04b-AI_Policy-ai_regs_and_laws.Rmd
Just making it flow a bit better between the chapter on AI regulations and the case studies.
=> [AI Policy] Clean up language about industry-specific policies

00-intro.Rmd
making the combined course on coursera and noticed this was empty
=> removing empty curriculum section

00-intro.Rmd, 01a-AI_Possibilities-intro.Rmd, 01b-AI_Possibilities-what_is_ai.Rmd, 01c-AI_Possibilities-how_ai_works.Rmd, 01d-AI_Possibilities-ai_types.Rmd, 01e-AI_Possibilities-possibilities.Rmd, 01f-AI_Possibilities-ground_rules.Rmd, 03a-Determining-AI-Needs-intro.Rmd, 03b-Determining-AI-Needs-components.Rmd, 03c-Determining-AI-Needs-determining-needs.Rmd, 03d-Determining-AI-Needs-knowledge.Rmd, 03e-Determining-AI-Needs-security.Rmd, 03f-Determining-AI-Needs-interface.Rmd, 03g-Determining-AI-Needs-evaluation.Rmd, 04b-AI_Policy-ai_regs_and_laws.Rmd, 04c-AI_Policy-how_to_navigate.Rmd, 04d-AI_Policy-data_laws.Rmd, 04e-AI_Policy-creating_your_ai_policy.Rmd, assets/style.css, index.Rmd
Commenting out the video sections for now. We are apparently getting some traffic on the course and want to avoid confusing people before we get the videos on YouTube.
=> Cut video sections // other tweaks

02b-Avoiding_Harm-concepts.Rmd
=> Ethics updates

.github/workflows/docker-test.yml
tj-actions/verify-changed-files@17
Related to https://github.com/jhudsl/OTTR_Template/issues/716
Related to https://github.com/fhdsl/AI_for_Decision_Makers/security/dependabot/1
=> Bump version to tj-actions/verify-changed-files@17
